### PR TITLE
Feature/dockerized app

### PR DESCRIPTION
**Pull request by samueldg**
Really love this project! I thought it could benefit from a simple Docker build/run setup.
Eventually worth considering pushing that on the registry, so people could pull the image and run it without installing any dependencies!

### CODE REVIEW

**Comment by nichochar** [comment]
The check that failed will be solved by merging https://github.com/pinterest/snappass/pull/11

**Comment by nichochar** [comment]
Hi @samueldg , thanks for the PR! Great idea to dockerize this. 
I have one question: I'm not very proficient in docker, and I'm wondering if it's a better idea to have REDIS run on the same docker, or if it's better to have it running in a separate one (that is my understanding of what your docker-compose file is for.

**Comment by samueldg** [comment]
Thanks for the quick replies @nichochar!

It is generally advised to run, as much as possible, only one process per container (ref. [Docker best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/run-only-one-process-per-container))

A few advantages off the top of my head:
- Simplicity - Using python + redis base images, instead of doing manual steps in another base image;
- Easier to upgrade - If we want to upgrade the Redis image, we can simply update the tag (now I'm using "latest" which will result in that behaviour);
- Scalability - We can scale the python app container if we need to without running more Redis instances. For example, if someone really wanted to have more servers running, it would be as easy as running [docker-compose scale](https://docs.docker.com/compose/reference/scale/) and load balancing. All servers would talk to the same Redis store;
- Integration in existing tools - orchestration and monitoring tools will be simpler to use as the processes can be interacted with separately.

**Comment by samueldg** [comment]
@nichochar Rebase done.

**Comment by yongwen** [comment]
looks good. agree that the redis is better separated from snappass's dockerfile. Thanks for the dockerizing snappass.

**Comment by nichochar** [comment]
Great! Thanks @samueldg and @yongwen !

**Pull request merged**
