### PR TITLE
Add ENV variables options

### PR DESCRIPTION
**Pull request by nichochar**
This is a reproduction of https://github.com/pinterest/snappass/pull/3 (unfortunately that build is broken because of old, flakey tests, and author is unresponsive. 

The idea is still valid though, so I reproduced his work here.

### CODE REVIEW

**Comment by jparise** [comment]
Perhaps we should just add a single `REDIS_URL` environmental variable that is passed to `Client.from_url`?

https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L454

**Comment by nichochar** [comment]
We could, but in that case do you suggest changing the way we [instantiate redis](https://github.com/pinterest/snappass/blob/2855e5b9b678c13f9ff524fca02411fcd348d153/snappass/main.py#L18) and use the `from_url`?

I was just extending our current call to be parametrizable. I can look into calling redis differently.

**Comment by jparise** [comment]
Yes, that's my suggestion. That would give us a single way for people to set all of the connection parameters (including username and password).

**Comment by nichochar** [comment]
I will merge this for now, since it gives more custom ability to tune your connection. But I added [a ticket](https://github.com/pinterest/snappass/issues/28) as per your suggestion to use URL and instantiate the client with a different call.

**Pull request merged**
