### PR TITLE
Intermediary page

### PR DESCRIPTION
**Pull request by jameswthorne**
I built the **intermediary-page** branch on top of the changes in the **ui-improvements** branch.

The relevant changes for the **intermediary-page** branch are in file **main.py** and the new file **password_link.html**.

There's only minor changes in the other HTML template files because of pathing issues due to appending **/reveal** to the URL.

### CODE REVIEW

**Comment by nichochar** [comment]
It will be easier to consider this PR once we have merged the bootstrap upgrade one.

**Comment by nichochar** [comment]
Could you rebase master and push, since I merged the UI improvements one? That way most of the diffs will disappear in the PR. Thanks.

**Comment by jameswthorne** [comment]
Rebase complete. All tests are good to go.

**Comment by nichochar** [comment]
I prefer the bot interception design proposed in #46 
It doesn't change the user experience, which is a win in my opinion. We won't go ahead with this one, thanks for the PR though @jameswthorne

**Pull request closed without merging**
