### PR TITLE
Add button to copy link/password to clipboard

### PR DESCRIPTION
**Pull request by samueldg**
- Using clipboard.js
- On browsers not supporting evalCommand(), the text will be selected,
  and the keyboard shortcut displayed, depending on platform.
  (tested on Safari)
- Now using Bootstrap readonly text form, instead of a header,
  to display the passwords and generated links;
- Using fontawesome to get a clipboard icon (like GitHub, GitLab, etc.)
- fontawesome and clipboard.js are pulled from a CDN.

Looks like this:
copy_to_clipboard

And auto-selection + keyboard shortcut on safari:
copy_not_supported

Feel free to try it out and suggest improvements.

### CODE REVIEW

**Comment by jparise** [comment]
Given the sensitive nature of passwords in general, I wonder if this would be a case where all JavaScript resources should be best served from the origin instead of using external CDN-hosted sources.

**Comment by samueldg** [comment]
@jparise Good point. I can update that, and I guess pull out jquery as well, which is also currently delivered that way.

**Comment by nichochar** [comment]
Is it possible to do this without the jquery dependency @samueldg ?
I like the feature, but I would rather not add dependencies unless they are absolutely necessary. I wonder how hard it would be to do this without jquery, or with a smaller, more specific lib

**Comment by voidpirate** [comment]
@jparise 

I think if loading resources via CDN provider, the very least should include [SubResource Integrity](https://www.w3.org/TR/SRI/) for each resource being loaded.

**Comment by jparise** [comment]
SubResource Integrity sounds useful, but browser support isn't quite there yet: http://caniuse.com/#feat=subresource-integrity

**Comment by samueldg** [comment]
@jparise I added the clipboardjs scripts in the static directory, so they are not pulled from a CDN anymore. I also pulled jquery in there, cause I guess the same reasoning applies.

@nichochar Regarding jquery, it's not a dependency I added: it's already there (I guess it's needed for some parts of bootstrap?). The lib I used is indeed smaller and more specific :) 

I'm waiting for your feedback!

**Comment by nichochar** [comment]
Looks great. I wasn't aware that jquery was already there Since it is, this is great. Thanks

**Comment by nichochar** [comment]
Thanks for contributing @samueldg !

**Pull request merged**
