### PR TITLE
Return the password as string instead of byte

### PR DESCRIPTION
**Pull request by clmoreno**
`redis_client.get()` returns the password as byte, so password is printed as: **b'password'** and some people thinks that the **b''** is part of the password.

This commit ensures that the value returned by `get_password()` is a string, to be able to print the password literally as it is.

before the change:
image

after the cahnge:
image

### CODE REVIEW

**Comment by nichochar** [comment]
Thanks for this @clmoreno ! Do you think it would be possible to add a small test, that verifies that the type of what we receive is a string?
Once the test is in, I will merge.

**Comment by clmoreno** [comment]
sure, i will work on it.

**Comment by samueldg** [comment]
@clmoreno @nichochar I had to do a similar fix for https://github.com/pinterest/snappass/pull/19. Note the explicit None check though, as theoretically the key could be an empty string...

**Comment by clmoreno** [comment]
@samueldg seems great! :)

**Comment by nichochar** [comment]
This has been added as part of https://github.com/pinterest/snappass/pull/19

Thanks for the PR though @clmoreno , hope you come up with more good ideas !

**Pull request closed without merging**
