### PR TITLE
Update docker-compose file to version 2

### PR DESCRIPTION
**Pull request by ebuildy**
And snappass container will be built from Dockerfile since there is no official image (yet..)

### CODE REVIEW

**Comment by nichochar** [comment]
Thanks for the PR @ebuildy ! I am not familiar with version2 of docker-compose, but I have heard that docker often makes backwards breaking changes to their stuff.

Is this change backwards compatible? How can we verify?

Thanks!

**Comment by ebuildy** [comment]
I think this change will not be compatible against old docker-compose releases (not Docker, but docker-compose). 

I did the PR because I have to use custom networks configuration from version 2 to run it in my company network.

**Comment by gengmao** [comment]
LGTM. We don't need to continue support old version of docker-compose

**Comment by nichochar** [comment]
Thanks @gengmao, merging.

**Comment by nichochar** [comment]
FYI, more information on this transition https://medium.com/@giorgioto/docker-compose-yml-from-v1-to-v2-3c0f8bb7a48e#.ginwdm71e

**Pull request merged**
